for ii = 1:length( rxx )
    for isim = 1:svsims
        for jj = 1:ii
            s_delta{1}( jj, ii, isim ) = sum( diag( ...
                ( eye( nk ) + s_Q{jj}( :, :, isim ) ) ...
                / ( eye( nk ) + s_Q{ii}( :, :, isim ) ) ) ) / nk;
            s_delta{2}( jj, ii, isim ) = sum( diag( ...
                s_Qo{jj}( :, :, isim ) * s_Q{ii}( :, :, isim ) ) );
            s_delta{3}( jj, ii, isim ) = norm( ...
                s_Q{jj}( :, :, isim ) - s_Q{ii}( :, :, isim ) );
            s_delta{4}( jj, ii, isim ) = sum( abs( diag( ...
                s_Q{jj}( :, :, isim ) - s_Q{ii}( :, :, isim ) ) ) );
            s_delta{5}( jj, ii, isim ) = norm( ...
                s_Q{jj}( :, :, isim ) - s_Q{ii}( :, :, isim ), 'fro' );
            s_delta{6}( jj, ii, isim ) = 1 - sum( diag( ...
                s_Q{jj}( :, :, isim ) * s_Q{ii}( :, :, isim ) ) ) ...
                / norm( s_Q{jj}( :, :, isim ), 'fro' ) ...
                / norm( s_Q{ii}( :, :, isim ), 'fro' );
        end
    end
end